### ISSUE TITLE
Package as pre-built wheels 

### ISSUE THREAD

**Issue by pombredanne** [repology/py-libversion#10]
It would be great to also package libversion as pre-built wheels. In particular I could use a pre-built slower pure Python wheel and pre-built wheels for Linux, Windows and macOS all 64 bits and Intel processors. That's for use in ScanCode toolkit and VulnerableCode.
I can chip in an help there alright.

**Comment by AMDmi3** [comment]
I do not distribute binaries.

**Comment by pombredanne** [comment]
Fair enough! Thanks for the super fast reply anyway.
